import puppeteer, { Browser, Page } from 'puppeteer';

export interface CorreosCredentials {
  email: string;
  password: string;
}

export interface SenderInfo {
  idType: string;        // "Física", "Dimex", "Pasaporte", "Jurídica"
  idNumber: string;      // Número de identificación
  name: string;          // Nombre completo
  phone: string;         // Teléfono
  email: string;         // Correo electrónico
  province: string;      // Provincia
  canton: string;        // Cantón
  district: string;      // Distrito
  postalCode: string;    // Código postal
  address: string;       // Señas exactas de dirección
}

export interface OrderData {
  orderId: string;
  customerName: string;
  phone: string;
  idType?: string;       // Tipo de identificación (optional)
  idNumber?: string;     // Número de identificación (optional)
  email?: string;
  address: string;       // Señas exactas de dirección del destinatario
  province: string;
  canton: string;
  district: string;
  postalCode?: string;   // Auto-generated by Correos
  deliveryType: 'Domicilio' | 'Sucursal' | 'Punto de correo';  // Tipo de Envío
  product: string;       // Product name for "Detalle del envío"
  quantity: number;
  comments?: string;
}

export interface GuiaResult {
  success: boolean;
  guiaNumber?: string;
  trackingNumber?: string;
  error?: string;
  orderId: string;
  pdfDownloaded?: boolean;
  pdfBuffer?: Buffer;
  pdfFileName?: string;
}

export class CorreosAutomation {
  private browser: Browser | null = null;
  private page: Page | null = null;
  private credentials: CorreosCredentials;
  private senderInfo?: SenderInfo;
  private debugMode: boolean;

  constructor(credentials: CorreosCredentials, senderInfo?: SenderInfo) {
    this.credentials = credentials;
    this.senderInfo = senderInfo;
    this.debugMode = process.env.CORREOS_DEBUG === '';
  }

  async initialize(): Promise<void> {
    try {
      // Create downloads directory if it doesn't exist
      const fs = require('fs');
      const path = require('path');
      const downloadPath = path.join(process.cwd(), 'downloads');
      
      if (!fs.existsSync(downloadPath)) {
        fs.mkdirSync(downloadPath, { recursive: true });
        console.log(`Created downloads directory: ${downloadPath}`);
      }
      
      const headlessEnv = process.env.CORREOS_HEADLESS?.toLowerCase();
      const headless = (this.debugMode || headlessEnv === 'false') ? false : true;

      console.log(`Launching Correos automation browser (headless: ${headless})`);

      this.browser = await puppeteer.launch({
        headless,
        args: [
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--disable-accelerated-2d-canvas',
          '--no-first-run',
          '--no-zygote',
          '--disable-gpu',
          '--window-size=1920,1080',
          '--disable-features=PasswordManager',
          '--disable-password-manager-reauthentication',
          '--disable-save-password-bubble',
          '--disable-blink-features=AutomationControlled'
        ]
      });

      this.page = await this.browser.newPage();
      this.page.setDefaultNavigationTimeout(60000);
      this.page.setDefaultTimeout(30000);
      
      // Set user agent to avoid detection
      await this.page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36');
      
      // Set viewport
      await this.page.setViewport({ width: 1366, height: 768 });
      
      // Enable downloads and handle dialogs via CDP
      const client = await this.page.target().createCDPSession();
      
      // Set download behavior to allow and specify download path
      await client.send('Browser.setDownloadBehavior', {
        behavior: 'allow',
        downloadPath: downloadPath,
        eventsEnabled: true
      });
      
      // Also set page-level download behavior
      await client.send('Page.setDownloadBehavior', {
        behavior: 'allow',
        downloadPath: downloadPath
      });
      
      console.log(`Downloads will be saved to: ${downloadPath}`);
      
      // Auto-dismiss Chrome password manager dialogs
      this.page.on('dialog', async dialog => {
        console.log(`Dialog detected: ${dialog.type()} - ${dialog.message()}`);
        await dialog.dismiss();
        console.log('✓ Dialog dismissed');
      });
      
      console.log('Browser initialized successfully');
    } catch (error) {
      throw new Error(`Failed to initialize browser: ${error}`);
    }
  }

  async login(): Promise<boolean> {
    if (!this.page) {
      throw new Error('Browser not initialized');
    }

    try {
      console.log('Navigating to login page...');
      await this.page.goto('https://sucursal.correos.go.cr/login', {
        waitUntil: 'networkidle2',
        timeout: 30000
      });

      await new Promise(resolve => setTimeout(resolve, 2000));

      // Find and fill email field
      const emailSelectors = [
        'input[id="login"]',
        'input[name="login"]',
        'input[type="email"]',
        'input[name="email"]',
        'input[id="email"]',
        'input[name="username"]'
      ];

      let emailFilled = false;
      for (const selector of emailSelectors) {
        try {
          const element = await this.page.$(selector);
          if (element) {
            await element.type(this.credentials.email, { delay: 50 });
            console.log(`Email filled with selector: ${selector}`);
            emailFilled = true;
            break;
          }
        } catch (e) {
          continue;
        }
      }

      if (!emailFilled) {
        throw new Error('Could not find email field');
      }

      // Find and fill password field
      const passwordSelectors = [
        'input[type="password"]',
        'input[name="password"]',
        'input[id="password"]'
      ];

      let passwordFilled = false;
      for (const selector of passwordSelectors) {
        try {
          const element = await this.page.$(selector);
          if (element) {
            await element.type(this.credentials.password, { delay: 50 });
            console.log(`Password filled with selector: ${selector}`);
            passwordFilled = true;
            break;
          }
        } catch (e) {
          continue;
        }
      }

      if (!passwordFilled) {
        throw new Error('Could not find password field');
      }

      // Find and click login button
      const loginSelectors = [
        'button[type="submit"]',
        'input[type="submit"]',
        'button:has-text("Iniciar")',
        'button:has-text("Login")',
        'button:has-text("Entrar")'
      ];

      let loginClicked = false;
      for (const selector of loginSelectors) {
        try {
          const element = await this.page.$(selector);
          if (element) {
            await element.click();
            console.log(`Login button clicked with selector: ${selector}`);
            loginClicked = true;
            break;
          }
        } catch (e) {
          continue;
        }
      }

      if (!loginClicked) {
        // Try pressing Enter as fallback
        await this.page.keyboard.press('Enter');
      }

      // Wait for navigation
      await this.page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 15000 });
      
      console.log('Login successful');
      
      // Handle Chrome password breach warning dialog if it appears
      await this.dismissPasswordWarning();
      
      return true;
    } catch (error) {
      await this.captureScreenshot('login-error');
      throw new Error(`Login failed: ${error}`);
    }
  }

  /**
   * Dismiss Chrome password breach warning dialog
   */
  private async dismissPasswordWarning(): Promise<void> {
    if (!this.page) return;

    try {
      console.log('Attempting to dismiss any password warnings...');
      
      // In headless mode, password warnings don't appear
      // Just wait briefly and continue
      await new Promise(resolve => setTimeout(resolve, 500));
      console.log('✓ Password warning check complete (headless mode)');
      
    } catch (error) {
      console.warn('Could not dismiss password warning:', error);
    }
  }

  async navigateToGuiaCreation(): Promise<void> {
    if (!this.page) {
      throw new Error('Browser not initialized');
    }

    try {
      console.log('Navigating to guía creation page...');
      
      await this.page.goto('https://sucursal.correos.go.cr/sucursal/guide/create', {
        waitUntil: 'networkidle0',
        timeout: 20000
      });
      
      await new Promise(resolve => setTimeout(resolve, 1500));
      console.log('Navigated to guía creation page');
    } catch (error) {
      await this.captureScreenshot('navigation-error');
      throw new Error(`Failed to navigate to guía creation: ${error}`);
    }
  }

  /**
   * Helper method to select from dropdown by visible text
   */
  private async selectDropdownByText(page: Page, selectSelector: string, optionText: string): Promise<boolean> {
    try {
      await page.waitForSelector(selectSelector, { timeout: 5000 });
      
      // Ensure optionText is a string
      const searchText = String(optionText || '').trim();
      if (!searchText) {
        console.warn('Empty option text provided to selectDropdownByText');
        return false;
      }
      
      // Normalize text for comparison (remove accents)
      const normalizeText = (text: string) => {
        return text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
      };
      
      // Get all options
      const options = await page.$$eval(`${selectSelector} option`, (opts, text) => {
        const normalizeText = (str: string) => {
          return str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();
        };
        const searchNormalized = normalizeText(String(text));
        
        // Map all options
        const allOptions = opts.map(opt => ({
          value: opt.value,
          text: opt.textContent?.trim() || '',
          normalized: normalizeText(opt.textContent?.trim() || '')
        }));
        
        // Filter options - exclude empty values and placeholder text
        return allOptions
          .filter(opt => {
            // Skip empty values
            if (opt.value === '' || opt.value === '0') return false;
            
            // Skip placeholder text (Spanish)
            const placeholders = [
              'seleccione',
              'selecciona',
              'seleccionar',
              'select'
            ];
            const textLower = opt.normalized;
            if (placeholders.some(ph => textLower.startsWith(ph))) return false;
            
            return true;
          })
          .filter(opt => {
            // Exact match first
            if (opt.normalized === searchNormalized) return true;
            // Then check if option text contains search or vice versa
            return opt.normalized.includes(searchNormalized) || searchNormalized.includes(opt.normalized);
          })
          .map(opt => ({ value: opt.value, text: opt.text })); // Remove normalized field
      }, searchText);

      if (options.length > 0) {
        console.log(`Found ${options.length} matching options, selecting: ${options[0].text} (value: ${options[0].value})`);
        
        // Set the value directly and trigger change events
        const result = await page.evaluate((selector, value, text) => {
          const element = document.querySelector(selector) as HTMLSelectElement;
          if (!element) {
            return { success: false, error: 'Element not found' };
          }
          
          // Check if the option exists
          const option = Array.from(element.options).find(opt => opt.value === value);
          if (!option) {
            return { success: false, error: `Option with value "${value}" not found in select` };
          }
          
          // Focus the element
          element.focus();
          
          // Set the value
          element.value = value;
          
          // Also set selectedIndex for good measure
          element.selectedIndex = Array.from(element.options).indexOf(option);
          
          // Trigger all necessary events in the right order
          element.dispatchEvent(new Event('input', { bubbles: true }));
          element.dispatchEvent(new Event('change', { bubbles: true }));
          element.dispatchEvent(new Event('blur', { bubbles: true }));
          
          // Verify the value was set
          const actualValue = element.value;
          return { 
            success: actualValue === value, 
            actualValue,
            expectedValue: value
          };
        }, selectSelector, options[0].value, options[0].text);
        
        if (result.success) {
          console.log(`✓ Selected "${options[0].text}" from dropdown (verified)`);
          await new Promise(resolve => setTimeout(resolve, 1000)); // Wait for any onChange handlers and cascading updates
          return true;
        } else {
          console.warn(`✗ Failed to select dropdown: ${result.error || 'Value mismatch'}`);
          if (result.actualValue !== undefined) {
            console.warn(`  Expected: ${result.expectedValue}, Got: ${result.actualValue}`);
          }
          return false;
        }
      }
      
      console.warn(`No matching option found for: ${searchText}`);
      return false;
    } catch (error) {
      console.warn(`Failed to select from dropdown: ${error}`);
      return false;
    }
  }

  /**
   * Fill sender (remitente) information
   */
  private async fillSenderInfo(): Promise<void> {
    if (!this.page || !this.senderInfo) return;

    console.log('Filling sender (remitente) information...');
    const s = this.senderInfo;

    // ID Type dropdown
    await this.selectDropdownByText(
      this.page,
      'select[name*="idType"], select[id*="idType"], select[name*="tipoIdentificacion"]',
      s.idType
    );

    // ID Number
    await this.fillField('input[name*="idNumber"], input[id*="idNumber"], input[name*="numeroIdentificacion"]', s.idNumber);

    // Name
    await this.fillField('input[name*="senderName"], input[id*="senderName"], input[name*="nombreRemitente"]', s.name);

    // Phone
    await this.fillField('input[name*="senderPhone"], input[id*="senderPhone"], input[name*="telefonoRemitente"]', s.phone);

    // Email
    await this.fillField('input[name*="senderEmail"], input[id*="senderEmail"], input[name*="correoRemitente"]', s.email);

    // Province dropdown
    await this.selectDropdownByText(
      this.page,
      'select[name*="senderProvince"], select[id*="senderProvince"], select[name*="provinciaRemitente"]',
      s.province
    );

    await new Promise(resolve => setTimeout(resolve, 1000)); // Wait for canton dropdown to populate

    // Canton dropdown
    await this.selectDropdownByText(
      this.page,
      'select[name*="senderCanton"], select[id*="senderCanton"], select[name*="cantonRemitente"]',
      s.canton
    );

    await new Promise(resolve => setTimeout(resolve, 1000)); // Wait for district dropdown to populate

    // District dropdown
    await this.selectDropdownByText(
      this.page,
      'select[name*="senderDistrict"], select[id*="senderDistrict"], select[name*="distritoRemitente"]',
      s.district
    );

    // Postal Code
    await this.fillField('input[name*="senderPostalCode"], input[id*="senderPostalCode"], input[name*="codigoPostalRemitente"]', s.postalCode);

    // Address
    await this.fillField('textarea[name*="senderAddress"], input[name*="senderAddress"], textarea[name*="direccionRemitente"]', s.address);

    console.log('Sender information filled');
  }

  /**
   * Fill package details (Datos del paquete)
   */
  private async fillPackageDetails(orderData: OrderData): Promise<void> {
    if (!this.page) return;

    console.log('Filling package details...');

    // Detalle del envío - Product name and quantity
    const packageDetail = `${orderData.product} (Cantidad: ${orderData.quantity})`;
    await this.fillField(
      'textarea[name="box_detail"], textarea[id="box_detail"]',
      packageDetail
    );

    console.log(`Package details filled: ${packageDetail}`);
  }

  /**
   * Fill recipient (destinatario) information
   */
  private async fillRecipientInfo(orderData: OrderData): Promise<void> {
    if (!this.page) return;

    console.log('Filling recipient information...');

    // Tipo de identificación (optional)
    if (orderData.idType) {
      await this.selectDropdownByText(
        this.page,
        'select[name*="tipoIdentificacion"]:not([name*="remitente"]), select[id*="tipoIdentificacion"]:not([id*="remitente"])',
        orderData.idType
      );
    }

    // Número de identificación (optional)
    if (orderData.idNumber) {
      await this.fillField(
        'input[name*="numeroIdentificacion"]:not([name*="remitente"]), input[id*="numeroIdentificacion"]:not([id*="remitente"])',
        orderData.idNumber
      );
    }

    // Nombre completo *
    await this.fillField(
      'input[name="destination_name"], input[id="destination_name"]',
      orderData.customerName
    );

    // Teléfono *
    await this.fillField(
      'input[name="destination_phone"], input[id="destination_phone"]',
      orderData.phone
    );

    // Tipo de Envío * - Domicilio, Sucursal, or Punto de correo (PuntoCorreos)
    console.log(`Selecting delivery type: ${orderData.deliveryType}`);
    const deliveryTypeValue = orderData.deliveryType === 'Punto de correo' ? 'PuntoCorreos' : orderData.deliveryType;
    const deliveryTypeSelected = await this.selectDropdownByText(
      this.page,
      'select[name="destination_type"], select[id="destination_type"]',
      deliveryTypeValue
    );
    console.log(`Delivery type selected: ${deliveryTypeSelected}`);

    await new Promise(resolve => setTimeout(resolve, 500));

    // Provincia * - Select province first
    console.log(`Selecting province: ${orderData.province}`);
    await this.selectDropdownByText(
      this.page,
      'select[name="provincia"], select[id="provincia"]',
      orderData.province
    );

    // Wait for canton dropdown to populate after province selection
    console.log('Waiting for canton dropdown to populate...');
    await new Promise(resolve => setTimeout(resolve, 2500));
    
    // Verify canton dropdown has options
    const cantonOptionsCount = await this.page.evaluate(() => {
      const select = document.querySelector('select[name="canton"]') as HTMLSelectElement;
      return select ? select.options.length : 0;
    });
    console.log(`Canton dropdown has ${cantonOptionsCount} options`);
    
    console.log(`Selecting canton: ${orderData.canton}`);

    // Cantón * - Select canton (options depend on province)
    await this.selectDropdownByText(
      this.page,
      'select[name="canton"], select[id="canton"]',
      orderData.canton
    );

    // Wait for district dropdown to populate after canton selection
    console.log('Waiting for district dropdown to populate...');
    await new Promise(resolve => setTimeout(resolve, 2500));
    
    // Verify district dropdown has options
    const districtOptionsCount = await this.page.evaluate(() => {
      const select = document.querySelector('select[name="distrito"]') as HTMLSelectElement;
      return select ? select.options.length : 0;
    });
    console.log(`District dropdown has ${districtOptionsCount} options`);
    
    console.log(`Selecting district: ${orderData.district}`);

    // Distrito * - Select district (options depend on canton)
    await this.selectDropdownByText(
      this.page,
      'select[name="distrito"], select[id="distrito"]',
      orderData.district
    );

    // Wait for postal code to auto-populate after district selection
    console.log('Waiting for postal code to auto-populate...');
    await new Promise(resolve => setTimeout(resolve, 2500));
    console.log('Postal code should be auto-populated now');

    // Señas exactas de dirección del destinatario *
    await this.fillField(
      'textarea[name="destination_direction"], textarea[id="destination_direction"]',
      orderData.address
    );

    console.log('Recipient information filled');
    
    // Take a screenshot for debugging
    await this.captureScreenshot('correos-form-filled', { fullPage: true });
  }

  /**
   * Helper to fill a field with multiple selector attempts
   */
  private async fillField(selectors: string, value: string): Promise<boolean> {
    if (!this.page || !value) return false;

    const selectorList = selectors.split(',').map(s => s.trim());
    
    for (const selector of selectorList) {
      try {
        await this.page.waitForSelector(selector, { timeout: 3000 });
        
        // Method 1: Set value directly via JavaScript and trigger all events
        const filled = await this.page.evaluate((sel, val) => {
          const element = document.querySelector(sel) as HTMLInputElement | HTMLTextAreaElement;
          if (!element) return false;
          
          // Focus the element
          element.focus();
          
          // Set the value
          element.value = val;
          
          // Trigger all necessary events
          element.dispatchEvent(new Event('input', { bubbles: true }));
          element.dispatchEvent(new Event('change', { bubbles: true }));
          element.dispatchEvent(new Event('blur', { bubbles: true }));
          
          // Also trigger keyup/keydown for good measure
          element.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true }));
          element.dispatchEvent(new KeyboardEvent('keyup', { bubbles: true }));
          
          return true;
        }, selector, value);
        
        if (filled) {
          console.log(`Filled field ${selector} with: ${value}`);
          await new Promise(resolve => setTimeout(resolve, 200)); // Small delay for UI update
          return true;
        }
      } catch (e) {
        continue;
      }
    }
    
    console.warn(`Could not find field with selectors: ${selectors}`);
    return false;
  }

  /**
   * Submit the guía form
   */
  private async submitForm(): Promise<void> {
    if (!this.page) return;

    console.log('Submitting form...');

    // Take a screenshot before submitting
    await this.captureScreenshot('before-submit');

    // Wait a bit to ensure form validation is complete
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Click the "Crear guía" button - try multiple approaches
    const submitSelectors = [
      'input[id="btnCrear"]',
      'input[name="commit"]',
      'input[type="submit"].btn-success',
      '.btn-success[type="submit"]',
      'input[value*="Crear"]'
    ];

    let clicked = false;
    for (const selector of submitSelectors) {
      try {
        // Check if button exists and is visible
        const buttonInfo = await this.page.evaluate((sel) => {
          const btn = document.querySelector(sel) as HTMLInputElement;
          if (!btn) return { exists: false };
          
          const rect = btn.getBoundingClientRect();
          const style = window.getComputedStyle(btn);
          
          return {
            exists: true,
            visible: style.display !== 'none' && style.visibility !== 'hidden',
            disabled: btn.disabled,
            inViewport: rect.top >= 0 && rect.left >= 0,
            value: btn.value,
            type: btn.type,
            className: btn.className
          };
        }, selector);
        
        console.log(`Button check for ${selector}:`, buttonInfo);
        
        if (!buttonInfo.exists) continue;
        
        // Scroll button into view
        await this.page.evaluate((sel) => {
          const btn = document.querySelector(sel);
          if (btn) {
            btn.scrollIntoView({ behavior: 'smooth', block: 'center' });
          }
        }, selector);
        
        await new Promise(resolve => setTimeout(resolve, 500));
        
        // Try clicking with page.click() first
        try {
          // Click and wait for navigation or network activity
          await Promise.all([
            this.page.click(selector, { delay: 100 }),
            // Wait for either navigation or network idle
            Promise.race([
              this.page.waitForNavigation({ waitUntil: 'networkidle0', timeout: 5000 }).catch(() => null),
              new Promise(resolve => setTimeout(resolve, 2000))
            ])
          ]);
          
          console.log(`✓ Clicked submit button with page.click(): ${selector}`);
          clicked = true;
          break;
        } catch (clickError) {
          console.warn(`page.click() failed for ${selector}:`, clickError);
          
          // Try with evaluate as fallback
          const result = await this.page.evaluate((sel) => {
            const btn = document.querySelector(sel) as HTMLElement;
            if (btn) {
              // Check for validation errors first
              const form = btn.closest('form');
              if (form) {
                // Check if form is valid
                const isValid = (form as HTMLFormElement).checkValidity();
                console.log('Form validity:', isValid);
                
                if (!isValid) {
                  // Report validation errors
                  const invalidFields = Array.from(form.querySelectorAll(':invalid'));
                  console.log('Invalid fields:', invalidFields.map(f => ({
                    name: (f as HTMLInputElement).name,
                    value: (f as HTMLInputElement).value,
                    validationMessage: (f as HTMLInputElement).validationMessage
                  })));
                }
              }
              
              // Try multiple click methods
              btn.click();
              btn.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true }));
              
              // Also try submitting the form directly
              if (form) {
                form.submit();
              }
              return true;
            }
            return false;
          }, selector);
          
          if (result) {
            console.log(`✓ Clicked submit button via evaluate: ${selector}`);
            clicked = true;
            break;
          }
        }
      } catch (e) {
        console.warn(`Failed to process selector ${selector}:`, e);
        continue;
      }
    }

    if (!clicked) {
      console.error('❌ Failed to click submit button!');
      await this.captureScreenshot('submit-failed');
    }

    // Check what happened after click
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    const pageState = await this.page.evaluate(() => {
      const bodyText = document.body.textContent || '';
      
      // Look for specific error messages
      const errorMessages: string[] = [];
      const errorElements = document.querySelectorAll('.text-danger, .alert-danger, .error, [class*="error"]');
      errorElements.forEach(el => {
        const text = el.textContent?.trim();
        if (text && text.length > 0 && text.length < 200) {
          errorMessages.push(text);
        }
      });
      
      return {
        url: window.location.href,
        hasCreandoGuia: bodyText.includes('Creando Guía') || bodyText.includes('Creando Guia'),
        hasValidationError: errorMessages.length > 0,
        errorMessages: errorMessages,
        hasSuccess: bodyText.includes('éxito') || bodyText.includes('exitoso') || bodyText.includes('creada'),
        visibleText: bodyText.substring(0, 500)
      };
    });
    
    console.log('Page state after click:', pageState);
    
    // If there are validation errors, log them and take a screenshot
    if (pageState.hasValidationError && pageState.errorMessages.length > 0) {
      console.error('❌ Form validation errors detected:', pageState.errorMessages);
      await this.captureScreenshot('validation-errors', { fullPage: true });
    }
    
    // Wait for the "Creando Guía, espere por favor" dialog
    console.log('Waiting for guía creation...');
    
    // Look for the creation dialog
    try {
      await this.page.waitForFunction(
        () => {
          const bodyText = document.body.textContent || '';
          return bodyText.includes('Creando Guía') || bodyText.includes('Creando Guia');
        },
        { timeout: 10000 }
      );
      console.log('✓ Detected "Creando Guía" dialog');

      // Wait for the guía to be created (dialog processing)
      await new Promise(resolve => setTimeout(resolve, 3000));
      
      // Click OK button on the "Creando Guía" dialog
      const okClicked = await this.page.evaluate(() => {
        const buttons = Array.from(document.querySelectorAll('button'));
        const okButton = buttons.find(btn => {
          const text = btn.textContent?.trim().toUpperCase();
          return text === 'OK';
        }) as HTMLElement;
        
        if (okButton) {
          okButton.click();
          return true;
        }
        return false;
      });
      
      if (okClicked) {
        console.log('✓ Clicked OK on creation dialog');
        // Wait for success page to load
        await new Promise(resolve => setTimeout(resolve, 3000));
      } else {
        console.warn('⚠ Could not find OK button, trying Enter key');
        await this.page.keyboard.press('Enter');
        await new Promise(resolve => setTimeout(resolve, 3000));
      }
      
      // Take screenshot of success page
      await this.captureScreenshot('success-page');

    } catch (e) {
      console.warn('⚠ No creation dialog detected');
      await this.captureScreenshot('no-dialog');
    }

    console.log('Form submitted');
  }

  // ... (rest of the code remains the same)
  /**
   * Handle the "¿Deseas crear otra guía?" dialog
   */
  private async handleCreateAnotherDialog(createAnother: boolean): Promise<void> {
    if (!this.page) return;

    try {
      // Wait for the dialog to appear
      await this.page.waitForFunction(
        () => document.body.textContent?.includes('Deseas crear otra guía'),
        { timeout: 10000 }
      );

      console.log('Found "Deseas crear otra guía?" dialog');
      await new Promise(resolve => setTimeout(resolve, 1000));

      if (createAnother) {
        // Click "Sí, crear otra guía" button
        const clicked = await this.page.evaluate(() => {
          const buttons = Array.from(document.querySelectorAll('button, a'));
          const yesButton = buttons.find(btn => 
            btn.textContent?.includes('Sí, crear otra guía') ||
            btn.textContent?.includes('Si, crear otra guia')
          ) as HTMLElement;
          
          if (yesButton) {
            yesButton.click();
            return true;
          }
          return false;
        });

        if (clicked) {
          console.log('✓ Clicked "Sí, crear otra guía"');
          await new Promise(resolve => setTimeout(resolve, 2000));
          // Wait for new form to load
          await this.page.waitForSelector('textarea[name="box_detail"]', { timeout: 5000 });
        }
      } else {
        // Click "Ver mis Guías" button
        const clicked = await this.page.evaluate(() => {
          const buttons = Array.from(document.querySelectorAll('button, a'));
          const noButton = buttons.find(btn => 
            btn.textContent?.includes('Ver mis Guías') ||
            btn.textContent?.includes('Ver mis Guias')
          ) as HTMLElement;
          
          if (noButton) {
            noButton.click();
            return true;
          }
          return false;
        });

        if (clicked) {
          console.log('✓ Clicked "Ver mis Guías"');
          // Wait for navigation to guías list
          await this.page.waitForNavigation({ waitUntil: 'networkidle0', timeout: 15000 }).catch(() => {});
          await new Promise(resolve => setTimeout(resolve, 2000));
          console.log('✓ Navigated to guías list page');
        }
      }
    } catch (error) {
      console.warn('⚠ Dialog handling error:', error);
    }
  }

  /**
   * Extract guía number from the page after creation
   */
  private async extractGuiaNumber(): Promise<string | null> {
    if (!this.page) return null;

    try {
      // The guía number should be visible in the "¿Deseas crear otra guía?" dialog
      // Wait for it to appear
      await new Promise(resolve => setTimeout(resolve, 500));
      
      // Take a screenshot to debug
      await this.captureScreenshot('guia-created');
      
      // Look for guía number in the page
      const guiaInfo = await this.page.evaluate(() => {
        const bodyText = document.body.textContent || '';
        
        console.log('Page text for guía extraction:', bodyText.substring(0, 500));
        
        // Look for the guía number in the success dialog or page
        // Common patterns: PY05869748CR, 10823199, etc.
        const patterns = [
          /PY\d{8,10}CR/i,  // PY########CR format
          /\bPY\d{8,10}\b/i,  // PY######## without CR
          /Guía[:\s#]*(\d{7,10})/i,
          /Número[:\s]+(\d{7,10})/i,
          /Guide[:\s#]+(\d{7,10})/i,
          /creada[:\s]+(\d{7,10})/i,
          /exitosamente[:\s]+(\d{7,10})/i
        ];

        for (const pattern of patterns) {
          const match = bodyText.match(pattern);
          if (match) {
            const number = match[1] || match[0];
            // Skip if it looks like a postal code (5 digits) or phone (8 digits starting with specific patterns)
            if (!/^\d{5}$/.test(number) && !/^[67]\d{7}$/.test(number)) {
              console.log('Found guía number with pattern:', pattern, '→', number);
              return number.trim();
            }
          }
        }

        // Also check for any number in the dialog title, header, or success message
        const elements = Array.from(document.querySelectorAll('h1, h2, h3, h4, .modal-title, .dialog-title, .alert-success, .text-success, strong, b'));
        for (const element of elements) {
          const text = element.textContent || '';
          const match = text.match(/\d{7,10}/);
          if (match && !/^\d{5}$/.test(match[0]) && !/^[67]\d{7}$/.test(match[0])) {
            console.log('Found guía number in element:', element.tagName, '→', match[0]);
            return match[0];
          }
        }

        return null;
      });

      if (guiaInfo) {
        console.log(`✓ Extracted guía number: ${guiaInfo}`);
        return guiaInfo;
      }

      console.warn('⚠ Could not extract guía number from page');
      return null;
    } catch (error) {
      console.warn('Failed to extract guía number:', error);
      return null;
    }
  }

  /**
   * Dismiss any popup on the guías list page
   */
  private async dismissListPagePopup(): Promise<void> {
    if (!this.page) return;

    try {
      // Wait for page to load
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Try to dismiss any modal/popup
      const dismissed = await this.page.evaluate(() => {
        // Look for close buttons, OK buttons, or overlay elements
        const closeButtons = Array.from(document.querySelectorAll('button, a, .close, .modal-close, [aria-label="Close"]'));
        
        for (const btn of closeButtons) {
          const text = btn.textContent?.trim().toUpperCase() || '';
          const ariaLabel = (btn as HTMLElement).getAttribute('aria-label')?.toUpperCase() || '';
          
          if (text === 'OK' || text === 'CERRAR' || text === 'X' || 
              text === 'CLOSE' || ariaLabel.includes('CLOSE') || ariaLabel.includes('CERRAR')) {
            (btn as HTMLElement).click();
            console.log('Clicked popup button:', text || ariaLabel);
            return true;
          }
        }
        
        // Try pressing Escape
        return false;
      });

      if (dismissed) {
        console.log('✓ Dismissed list page popup');
      } else {
        console.log('Trying Escape key to dismiss popup...');
        await this.page.keyboard.press('Escape');
      }
      
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      // Take screenshot after dismissal
      await this.captureScreenshot('list-page-after-dismiss');
      
    } catch (error) {
      console.warn('Could not dismiss list page popup:', error);
    }
  }

  /**
   * Download PDF from the guías list page and return buffer
   */
  private async downloadGuiaPDF(customerName: string): Promise<{ success: boolean; buffer?: Buffer; fileName?: string }> {
    if (!this.page) return { success: false };

    try {
      console.log(`Looking for PDF download button for customer: ${customerName}`);
      
      // Wait for the table to load
      await this.page.waitForSelector('table, tr', { timeout: 5000 }).catch(() => {});
      await new Promise(resolve => setTimeout(resolve, 1000));

      // Take a screenshot to debug
      await this.captureScreenshot('guias-list');

      // Find the download URL first
      const downloadInfo = await this.page.evaluate((name) => {
        const normalizeText = (text: string) => {
          return text.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim();
        };
        
        const searchName = normalizeText(name);
        const rows = Array.from(document.querySelectorAll('tr'));
        
        console.log(`Searching for customer: ${name} (normalized: ${searchName})`);
        console.log(`Found ${rows.length} rows`);
        
        for (const row of rows) {
          const rowText = normalizeText(row.textContent || '');
          if (rowText.includes(searchName)) {
            console.log('Found matching row:', row.textContent?.substring(0, 100));
            
            // Look for PDF download link
            const downloadBtn = row.querySelector('a[href*="/guide/pdf/"], a[href*="/pdf/"]') as HTMLAnchorElement;
            if (downloadBtn) {
              console.log('Found download button:', downloadBtn.href);
              return { success: true, href: downloadBtn.href };
            } else {
              console.log('No download button in row');
              return { success: false, error: 'Download button not found in row' };
            }
          }
        }
        
        return { success: false, error: 'Customer row not found' };
      }, customerName);

      if (!downloadInfo.success || !downloadInfo.href) {
        console.warn(`❌ Could not find PDF: ${downloadInfo.error}`);
        return { success: false };
      }

      console.log(`✓ Found PDF URL: ${downloadInfo.href}`);

      // Download the PDF using fetch in the browser context
      const pdfData = await this.page.evaluate(async (url) => {
        try {
          const response = await fetch(url, {
            method: 'GET',
            credentials: 'include', // Include cookies for authentication
            headers: {
              'Accept': 'application/pdf'
            }
          });
          
          if (!response.ok) {
            return { success: false, error: `HTTP ${response.status}` };
          }
          
          const arrayBuffer = await response.arrayBuffer();
          const bytes = Array.from(new Uint8Array(arrayBuffer));
          return { success: true, bytes };
        } catch (error: any) {
          return { success: false, error: error.message };
        }
      }, downloadInfo.href);

      if (!pdfData.success || !pdfData.bytes) {
        console.warn(`❌ Failed to fetch PDF: ${pdfData.error}`);
        return { success: false };
      }

      // Convert byte array back to Buffer
      const buffer = Buffer.from(pdfData.bytes);
      
      // Extract filename from URL or use default
      const fileName = `guia-${customerName.replace(/\s+/g, '-')}-${Date.now()}.pdf`;
      
      console.log(`✓ Downloaded PDF: ${buffer.length} bytes`);
      
      return { success: true, buffer, fileName };
    } catch (error) {
      console.warn('Failed to download PDF:', error);
      return { success: false };
    }
  }

  /**
   * Main method to fill and submit the guía form
   */
  async fillGuiaForm(orderData: OrderData): Promise<GuiaResult> {
    if (!this.page) {
      throw new Error('Browser not initialized');
    }

    try {
      console.log(`Creating guía for order: ${orderData.orderId}`);

      // Wait for form to load
      await this.page.waitForSelector('textarea[name="box_detail"]', { timeout: 10000 });
      await new Promise(resolve => setTimeout(resolve, 1000));

      // Note: Sender information is pre-filled by Correos, no need to fill it
      // await this.fillSenderInfo();

      // Fill package details (Datos del paquete)
      await this.fillPackageDetails(orderData);

      // Fill recipient information (Datos del destinatario)
      await this.fillRecipientInfo(orderData);

      // Submit the form
      await this.submitForm();

      // Extract guía number
      const guiaNumber = await this.extractGuiaNumber();

      return {
        success: true,
        guiaNumber: guiaNumber || `PENDING-${orderData.orderId}`,
        trackingNumber: guiaNumber || undefined,
        orderId: orderData.orderId,
        pdfDownloaded: false // Will be downloaded later from the list
      };

    } catch (error) {
      await this.captureScreenshot(`error-${orderData.orderId}`);
      return {
        success: false,
        error: `Failed to create guía: ${error}`,
        orderId: orderData.orderId
      };
    }
  }

  /**
   * Generate a single guía
   */
  async generateGuia(orderData: OrderData): Promise<GuiaResult> {
    try {
      await this.initialize();
      await this.login();
      await this.navigateToGuiaCreation();
      const result = await this.fillGuiaForm(orderData);
      await this.close();
      return result;
    } catch (error) {
      await this.close();
      return {
        success: false,
        error: `Failed to generate guía: ${error}`,
        orderId: orderData.orderId
      };
    }
  }

  /**
   * Generate multiple guías in sequence
   */
  async generateMultipleGuias(orders: OrderData[]): Promise<GuiaResult[]> {
    const results: GuiaResult[] = [];

    try {
      await this.initialize();
      await this.login();
      await this.navigateToGuiaCreation();
      
      // Create guías for all orders
      for (let i = 0; i < orders.length; i++) {
        const order = orders[i];
        console.log(`Processing order ${i + 1}/${orders.length}: ${order.orderId}`);

        const result = await this.fillGuiaForm(order);
        results.push(result);

        // Handle "crear otra guía" dialog
        if (i < orders.length - 1) {
          // More orders to process, click "Sí, crear otra guía"
          await this.handleCreateAnotherDialog(true);
        } else {
          // Last order, go to list page to download PDFs
          console.log('✓ All guías created, going to download page...');
          await this.handleCreateAnotherDialog(false); // Click "Ver mis Guías"
        }
      }

      // Now on the guías list page - dismiss any popups and download PDFs
      console.log('On guías list page, dismissing popups...');
      await this.dismissListPagePopup();
      
      console.log('Downloading PDFs...');
      for (const result of results) {
        if (result.success && result.guiaNumber) {
          const order = orders.find(o => o.orderId === result.orderId);
          if (order) {
            const pdfResult = await this.downloadGuiaPDF(order.customerName);
            result.pdfDownloaded = pdfResult.success;
            if (pdfResult.success && pdfResult.buffer) {
              result.pdfBuffer = pdfResult.buffer;
              result.pdfFileName = pdfResult.fileName;
              console.log(`✓ PDF captured for ${order.customerName}: ${pdfResult.buffer.length} bytes`);
            }
            await new Promise(resolve => setTimeout(resolve, 1000));
          }
        }
      }

      await this.close();
      return results;

    } catch (error) {
      console.error('Error in generateMultipleGuias:', error);
      await this.close();
      return results.length > 0 ? results : [{
        success: false,
        error: `Failed to generate guías: ${error}`,
        orderId: 'BATCH'
      }];
    }
  }

  async close(): Promise<void> {
    if (this.browser) {
      await this.browser.close();
      this.browser = null;
      this.page = null;
      console.log('Browser closed');
    }
  }

  private async captureScreenshot(name: string, options: { fullPage?: boolean } = {}): Promise<void> {
    if (!this.page || !this.debugMode) {
      return;
    }

    const safeName = name.replace(/[^a-z0-9-_]/gi, '_').toLowerCase();
    const timestamp = Date.now();
    const filePath = `${safeName}-${timestamp}.png`;

    try {
      await this.page.screenshot({
        path: filePath as `${string}.png`,
        fullPage: options.fullPage ?? false
      });
      console.log(`Debug screenshot saved: ${filePath}`);
    } catch (error) {
      console.warn(`Failed to capture screenshot (${filePath}):`, error);
    }
  }
}

// Utility function to convert Order data to Correos format
export function convertOrderToCorreosFormat(order: any, deliveryType: 'Domicilio' | 'Sucursal' | 'Punto de correo' = 'Domicilio'): OrderData {
  return {
    orderId: order.orderId,
    customerName: order.customerName,
    phone: order.phone || '',
    idType: order.idType,
    idNumber: order.idNumber,
    email: order.email || '',
    address: order.address || order.direccion || '',
    province: order.province || order.provincia || '',
    canton: order.canton || '',
    district: order.district || order.distrito || '',
    postalCode: order.postalCode || order.codigoPostal,
    deliveryType: deliveryType,
    product: order.product || order.productName || 'Producto',
    quantity: order.quantity || order.cantidad || 1,
    comments: order.comments || order.observaciones
  };
}
