import { NextRequest, NextResponse } from 'next/server';
import { getTenantPrisma } from '@/lib/prisma-tenant';
import { authenticateAPIWithPermission } from '@/lib/auth-helpers';
import { logCreate, logUpdate, logDelete } from '@/lib/auditLogger';

export async function GET(request: NextRequest) {
  try {
    const auth = await authenticateAPIWithPermission(request, 'view_config');
    if (!auth.ok) return auth.response;
    
    const { tenantId } = auth;
    const prisma = getTenantPrisma(tenantId);

    const frequentCustomers = await prisma.client.findMany({
      where: { isActive: true },
      orderBy: [
        { totalOrders: 'desc' },
        { lastOrder: 'desc' }
      ]
    });

    return NextResponse.json({
      status: 'success',
      data: frequentCustomers
    });
  } catch (error) {
    console.error('Error fetching frequent customers:', error);
    return NextResponse.json(
      { error: 'Failed to fetch frequent customers' },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const auth = await authenticateAPIWithPermission(request, 'update_config');
    if (!auth.ok) return auth.response;
    
    const { tenantId, userId } = auth;
    const prisma = getTenantPrisma(tenantId);

    const body = await request.json();
    // Wizard sends: name, phone, email, address
    // API expects: name, phone, province, canton, district, email, username, address, business
    const { name, phone, email, address, province, canton, district, username, business } = body;

    const frequentCustomer = await prisma.client.create({
      data: {
        name,
        phone: phone || null,
        province: province || null,
        canton: canton || null,
        district: district || null,
        email: email || null,
        username: username || null,
        address: address || null,
        business: business || null,
        totalOrders: 0,
        totalSpent: 0,
        averageOrderValue: 0,
        firstOrder: new Date(),
        lastOrder: new Date(),
        isActive: true,
        isFavorite: false,
        isAutoGenerated: false,
        createdBy: userId,
        tenantId
      }
    });

    // Log audit trail
    try {
      await logCreate(request, 'frequent_customer', frequentCustomer.id, name, {
        name, phone, email, province, canton, district
      });
    } catch (auditError) {
      console.error('Failed to log customer creation audit:', auditError);
    }

    return NextResponse.json({
      status: 'success',
      data: frequentCustomer
    });
  } catch (error) {
    console.error('Error creating frequent customer:', error);
    return NextResponse.json(
      { error: 'Failed to create frequent customer' },
      { status: 500 }
    );
  }
}

export async function PUT(request: NextRequest) {
  try {
    const auth = await authenticateAPIWithPermission(request, 'update_config');
    if (!auth.ok) return auth.response;
    
    const { tenantId } = auth;
    const prisma = getTenantPrisma(tenantId);

    const body = await request.json();
    // Wizard sends: id, name, phone, email, address
    const { id, name, phone, email, address, province, canton, district, username, business, active } = body;

    // Get old values for audit
    const oldCustomer = await prisma.client.findUnique({ where: { id } });

    const frequentCustomer = await prisma.client.update({
      where: { id },
      data: {
        name,
        phone,
        province,
        canton,
        district,
        email,
        username,
        address,
        business,
        isActive: active !== undefined ? active : true,
        lastUpdated: new Date()
      }
    });

    // Log audit trail
    try {
      await logUpdate(request, 'frequent_customer', id, name, 
        { name: oldCustomer?.name, phone: oldCustomer?.phone, email: oldCustomer?.email },
        { name, phone, email }
      );
    } catch (auditError) {
      console.error('Failed to log customer update audit:', auditError);
    }

    return NextResponse.json({
      status: 'success',
      data: frequentCustomer
    });
  } catch (error) {
    console.error('Error updating frequent customer:', error);
    return NextResponse.json(
      { error: 'Failed to update frequent customer' },
      { status: 500 }
    );
  }
}

export async function DELETE(request: NextRequest) {
  try {
    const auth = await authenticateAPIWithPermission(request, 'update_config');
    if (!auth.ok) return auth.response;
    
    const { tenantId } = auth;
    const prisma = getTenantPrisma(tenantId);

    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');

    if (!id) {
      return NextResponse.json({ error: 'Customer ID is required' }, { status: 400 });
    }

    // Get customer data for audit
    const customer = await prisma.client.findUnique({ where: { id } });

    await prisma.client.update({
      where: { id },
      data: { isActive: false, lastUpdated: new Date() }
    });

    // Log audit trail
    try {
      await logDelete(request, 'frequent_customer', id, customer?.name || 'Unknown', 
        { name: customer?.name, phone: customer?.phone, email: customer?.email },
        'Cliente frecuente desactivado'
      );
    } catch (auditError) {
      console.error('Failed to log customer deletion audit:', auditError);
    }

    return NextResponse.json({
      status: 'success',
      message: 'Frequent customer deleted successfully'
    });
  } catch (error) {
    console.error('Error deleting frequent customer:', error);
    return NextResponse.json(
      { error: 'Failed to delete frequent customer' },
      { status: 500 }
    );
  }
}
