/**
 * Betsy theme palette — single source for Tailwind (tailwind.config.ts) and the generated
 * CSS variables (src/app/theme-palette.css, `npm run theme:gen`).
 *
 * Per-property theming: only the end of each scale that means "light UI" is remapped in dark:
 *   - backgrounds / gradients, borders / rings / dividers: shades 50–300 and `white`
 *   - text / placeholder / fill / stroke: shades 400–950 (`text-white` stays white)
 * Solid fills (bg-blue-600 + text-white, hover:bg-blue-700, bg-slate-900/40 scrims) and the
 * existing `dark:` utilities (which use 700–950 backgrounds / 50–300 text) are untouched.
 * Light values are Tailwind's defaults, so light mode renders exactly as before.
 *
 * Plain CommonJS on purpose: Tailwind's config loader, the generator script and tests all
 * read it without a build step.
 */
const colors = require('tailwindcss/colors')

const NEUTRALS = ['slate', 'gray', 'zinc', 'neutral', 'stone']
const HUES = [
  'red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal', 'cyan',
  'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose',
]

/** Dark surface ladder (Linear-style: lighter = more prominent). */
const DARK = {
  sidebar: '#07070C',
  canvas: '#0D0D14',
  surface: '#16161F',
  elevated: '#1D1D28',
}

const BG_SHADES = [50, 100, 200, 300]
const BD_SHADES = [50, 100, 200, 300]
const TX_SHADES = [400, 500, 600, 700, 800, 900, 950]

const NEUTRAL_DARK = {
  bg: { 50: '#1B1B26', 100: '#222230', 200: '#2B2B3A', 300: '#3A3A4D' },
  bd: { 50: '#1C1C27', 100: '#20202B', 200: '#262635', 300: '#34344A' },
  tx: { 400: '#7F8A9C', 500: '#94A3B8', 600: '#AEB8C7', 700: '#CBD5E1', 800: '#E2E8F0', 900: '#ECECF1', 950: '#F4F4F7' },
}
/** Hue tints = hue-500 mixed over the dark surface (muted, not the saturated -950s). */
const HUE_BG_MIX = { 50: 0.1, 100: 0.16, 200: 0.24, 300: 0.34 }
const HUE_BD_MIX = { 50: 0.14, 100: 0.22, 200: 0.32, 300: 0.45 }
/** Text on dark: darker shades flip to the light end of the same hue. */
const HUE_TX_FROM = { 400: 400, 500: 400, 600: 400, 700: 300, 800: 200, 900: 100, 950: 100 }

/**
 * Aurora tokens for colors that were arbitrary hex classes (`bg-[#F1EEFF]`, `text-[#5B3FE0]`…).
 * Generated by `node scripts/theme-hex-codemod.cjs` into aurora-hex-tokens.json via
 * `classifyHex` below; light = original hex exactly. Used as `bg-au-tint-f1eeff`, etc.
 */
function loadHexTokens() {
  try {
    return require('./aurora-hex-tokens.json')
  } catch {
    return {}
  }
}

function hexToRgb(hex) {
  const h = hex.replace('#', '')
  const full = h.length === 3 ? h.split('').map((c) => c + c).join('') : h
  const n = parseInt(full, 16)
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255]
}
function rgbToHex([r, g, b]) {
  return '#' + [r, g, b].map((v) => Math.round(v).toString(16).padStart(2, '0')).join('').toUpperCase()
}
function mix(fg, bg, amount) {
  const a = hexToRgb(fg)
  const b = hexToRgb(bg)
  return rgbToHex(a.map((v, i) => v * amount + b[i] * (1 - amount)))
}
const triplet = (hex) => hexToRgb(hex).join(' ')

function rgbToHsl([r, g, b]) {
  r /= 255
  g /= 255
  b /= 255
  const max = Math.max(r, g, b)
  const min = Math.min(r, g, b)
  const l = (max + min) / 2
  let h = 0
  let sat = 0
  if (max !== min) {
    const d = max - min
    sat = l > 0.5 ? d / (2 - max - min) : d / (max + min)
    h = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4
    h /= 6
  }
  return [h, sat, l]
}
function hslToHex(h, sat, l) {
  const f = (n) => {
    const k = (n + h * 12) % 12
    const a = sat * Math.min(l, 1 - l)
    return 255 * (l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1)))
  }
  return rgbToHex([f(0), f(8), f(4)])
}

const TEXT_PROPS = new Set(['text', 'fill', 'stroke', 'placeholder', 'caret', 'decoration'])
const FILL_PROPS = new Set(['bg', 'from', 'via', 'to'])
const LINE_PROPS = new Set(['border', 'ring', 'ring-offset', 'divide', 'outline'])

/**
 * Theme token for an arbitrary-hex class, or null when the literal is right in both themes
 * (solid brand fills, accent rings, already-light text on dark panels).
 *   - text under 4.5:1 on the dark surface → `ink-<hex>`: same hue, lightened to ≥ 6:1 (near-black → #F1F1F5)
 *   - light fill (L > 0.82)          → `tint-<hex>`: hue at 16 % over the surface (neutral if grey)
 *   - light border / ring (L > 0.82) → `line-<hex>`: hue at 32 % over the surface
 */
function classifyHex(prop, hex) {
  const key = hex.replace('#', '').toLowerCase()
  const [h, sat, l] = rgbToHsl(hexToRgb(hex))
  if (TEXT_PROPS.has(prop)) {
    // Only text that would be unreadable on the dark surface needs a token.
    if (contrast(hex, DARK.surface) >= 4.5) return null
    let dark = '#F1F1F5'
    if (sat >= 0.2 && l >= 0.12) {
      let lightness = 0.72
      dark = hslToHex(h, Math.min(sat, 0.9), lightness)
      while (contrast(dark, DARK.surface) < 6 && lightness < 0.95) {
        lightness += 0.02
        dark = hslToHex(h, Math.min(sat, 0.9), lightness)
      }
    }
    return { name: `ink-${key}`, light: hex, dark }
  }
  if (l <= 0.82) return null
  // Near-white / cream / grey tints (chroma < 6 %) go neutral. HSL saturation is misleading
  // this close to white (#FAFBFC reads as 25 % "saturated").
  const rgb = hexToRgb(hex)
  const neutral = (Math.max(...rgb) - Math.min(...rgb)) / 255 < 0.06
  const hue = hslToHex(h, 0.85, 0.62)
  if (FILL_PROPS.has(prop)) {
    return { name: `tint-${key}`, light: hex, dark: neutral ? NEUTRAL_DARK.bg[50] : mix(hue, DARK.surface, 0.16) }
  }
  if (LINE_PROPS.has(prop)) {
    return { name: `line-${key}`, light: hex, dark: neutral ? NEUTRAL_DARK.bd[200] : mix(hue, DARK.surface, 0.32) }
  }
  return null
}

function shadeHex(name, shade) {
  const v = colors[name] && colors[name][shade]
  if (!v) throw new Error(`Unknown Tailwind color ${name}-${shade}`)
  return v
}

/** Every palette variable with its light and dark value: [{ name, light, dark }]. */
function paletteVars() {
  const out = []
  const push = (name, light, dark) => out.push({ name, light, dark })
  for (const c of NEUTRALS) {
    for (const s of BG_SHADES) push(`--p-bg-${c}-${s}`, shadeHex(c, s), NEUTRAL_DARK.bg[s])
    for (const s of BD_SHADES) push(`--p-bd-${c}-${s}`, shadeHex(c, s), NEUTRAL_DARK.bd[s])
    for (const s of TX_SHADES) push(`--p-tx-${c}-${s}`, shadeHex(c, s), NEUTRAL_DARK.tx[s])
  }
  for (const c of HUES) {
    const base = shadeHex(c, 500)
    for (const s of BG_SHADES) push(`--p-bg-${c}-${s}`, shadeHex(c, s), mix(base, DARK.surface, HUE_BG_MIX[s]))
    for (const s of BD_SHADES) push(`--p-bd-${c}-${s}`, shadeHex(c, s), mix(base, DARK.surface, HUE_BD_MIX[s]))
    for (const s of TX_SHADES) push(`--p-tx-${c}-${s}`, shadeHex(c, s), shadeHex(c, HUE_TX_FROM[s]))
  }
  push('--p-bg-white', '#FFFFFF', DARK.surface)
  push('--p-bd-white', '#FFFFFF', DARK.surface)
  for (const [name, v] of Object.entries(loadHexTokens())) push(`--au-${name}`, v.light, v.dark)
  push('--au-sidebar', '#0E0D17', DARK.sidebar)
  return out
}

const ref = (v) => `rgb(var(${v}) / <alpha-value>)`

/** Tailwind `theme.extend` fragment (deep-merged over the default palettes). */
function tailwindExtend() {
  const role = (prefix, shades, withWhite) => {
    const obj = {}
    for (const c of [...NEUTRALS, ...HUES]) {
      obj[c] = {}
      for (const s of shades) obj[c][s] = ref(`--p-${prefix}-${c}-${s}`)
    }
    if (withWhite) obj.white = ref(`--p-${prefix}-white`)
    return obj
  }
  const au = {}
  for (const name of Object.keys(loadHexTokens())) au[name] = ref(`--au-${name}`)
  au.sidebar = ref('--au-sidebar')

  const bg = { ...role('bg', BG_SHADES, true), au }
  const bd = { ...role('bd', BD_SHADES, true), au }
  const tx = { ...role('tx', TX_SHADES, false), au }
  return {
    colors: { au },
    backgroundColor: bg,
    gradientColorStops: bg,
    borderColor: bd,
    ringColor: bd,
    ringOffsetColor: bd,
    divideColor: bd,
    outlineColor: bd,
    textColor: tx,
    placeholderColor: tx,
    fill: tx,
    stroke: tx,
  }
}

/** src/app/theme-palette.css contents. */
function buildCss() {
  const vars = paletteVars()
  const block = (sel, key) => `${sel} {\n${vars.map((v) => `  ${v.name}: ${triplet(v[key])};`).join('\n')}\n}\n`
  return [
    '/* GENERATED by `npm run theme:gen` from src/lib/theme/palette.cjs — do not edit by hand. */',
    '',
    block(':root', 'light'),
    block('html.dark', 'dark'),
    '/* Islands that keep their own look in any theme (dark sidebar, logistics, landing, QR/logo chips). */',
    block('.theme-static,\n.theme-light', 'light'),
    '/* Print is always light. */',
    `@media print {\n${block('  html.dark', 'light').replace(/\n(?=  --)/g, '\n  ')}}\n`,
  ].join('\n')
}

/** WCAG relative-luminance contrast. */
function contrast(a, b) {
  const lum = (hex) => {
    const [r, g, bl] = hexToRgb(hex).map((v) => {
      const c = v / 255
      return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
    })
    return 0.2126 * r + 0.7152 * g + 0.0722 * bl
  }
  const [x, y] = [lum(a), lum(b)].sort((m, n) => n - m)
  return (x + 0.05) / (y + 0.05)
}

module.exports = {
  NEUTRALS,
  HUES,
  DARK,
  NEUTRAL_DARK,
  classifyHex,
  loadHexTokens,
  HUE_TX_FROM,
  paletteVars,
  tailwindExtend,
  buildCss,
  contrast,
  mix,
}
