import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db';
import { authenticateAPIWithPermission } from '@/lib/auth-helpers';

export async function POST(request: NextRequest) {
  // This legacy helper replaces all tenant clients and inventory. It must
  // never be reachable in the shared production environment.
  if (process.env.NODE_ENV === 'production') {
    return new NextResponse(null, { status: 404 });
  }

  try {
    const auth = await authenticateAPIWithPermission(request, 'update_config');
    if (!auth.ok) return auth.response;
    const { tenantId, userId } = auth;

    // Create sample inventory items (replaces frequent products)
    const sampleProducts = [
      {
        name: 'Camiseta Básica',
        description: 'Camiseta',
        category: 'Ropa',
        sku: 'CAM-001',
        currentStock: 10,
        minStock: 5,
        unitCost: 15000,
        sellingPrice: 20000,
        isFavorite: true,
        isActive: true,
        totalSold: 0,
        createdBy: userId
      },
      {
        name: 'Pantalón Jean',
        description: 'Pantalón',
        category: 'Ropa',
        sku: 'PAN-001',
        currentStock: 8,
        minStock: 3,
        unitCost: 25000,
        sellingPrice: 35000,
        isFavorite: false,
        isActive: true,
        totalSold: 0,
        createdBy: userId
      },
      {
        name: 'Vestido Casual',
        description: 'Vestido',
        category: 'Ropa',
        sku: 'VES-001',
        currentStock: 5,
        minStock: 2,
        unitCost: 20000,
        sellingPrice: 30000,
        isFavorite: true,
        isActive: true,
        totalSold: 0,
        createdBy: userId
      }
    ];

    // Create sample clients (replaces frequent customers)
    const sampleCustomers = [
      {
        name: 'María González',
        phone: '8888-8888',
        province: 'San José',
        canton: 'San José',
        district: 'Carmen',
        email: 'maria@example.com',
        totalOrders: 5,
        totalSpent: 150000,
        averageOrderValue: 30000,
        firstOrder: new Date('2023-01-15'),
        lastOrder: new Date('2023-12-01'),
        isActive: true,
        isFavorite: true,
        isAutoGenerated: false,
        createdBy: userId
      },
      {
        name: 'Carlos Rodríguez',
        phone: '7777-7777',
        province: 'Alajuela',
        canton: 'Alajuela',
        district: 'Centro',
        email: 'carlos@example.com',
        totalOrders: 3,
        totalSpent: 90000,
        averageOrderValue: 30000,
        firstOrder: new Date('2023-03-10'),
        lastOrder: new Date('2023-11-15'),
        isActive: true,
        isFavorite: false,
        isAutoGenerated: false,
        createdBy: userId
      },
      {
        name: 'Ana Martínez',
        phone: '6666-6666',
        province: 'Cartago',
        canton: 'Cartago',
        district: 'Oriental',
        email: 'ana@example.com',
        totalOrders: 8,
        totalSpent: 240000,
        averageOrderValue: 30000,
        firstOrder: new Date('2023-02-01'),
        lastOrder: new Date('2023-12-10'),
        isActive: true,
        isFavorite: true,
        isAutoGenerated: false,
        createdBy: userId
      }
    ];

    await prisma.inventoryItem.deleteMany({ where: { tenantId } });
    await prisma.client.deleteMany({ where: { tenantId } });

    await prisma.inventoryItem.createMany({
      data: sampleProducts.map(p => ({ ...p, tenantId }))
    });

    await prisma.client.createMany({
      data: sampleCustomers.map(c => ({ ...c, tenantId }))
    });

    return NextResponse.json({
      status: 'success',
      message: 'Sample frequent products and customers created successfully'
    });
  } catch (error) {
    console.error('Error seeding frequent data:', error);
    return NextResponse.json(
      { error: 'Failed to seed frequent data' },
      { status: 500 }
    );
  }
}
