import type { Sql } from './postgres';
import { quoteIdent } from './postgres';

export interface SchemaDump {
  preSql: string;
  postSql: string;
}

/**
 * Generate restore-friendly DDL for all public base tables.
 * pre: CREATE TABLE (columns + PK)
 * post: UNIQUE, FK, indexes, sequences owned by columns
 */
export async function dumpPublicSchema(sql: Sql, tableNames: string[]): Promise<SchemaDump> {
  const pre: string[] = [
    '-- Generated by Betsy backup v1',
    'SET client_min_messages TO WARNING;',
    '',
  ];
  const post: string[] = [
    '-- Constraints, indexes, sequence sync',
    'SET client_min_messages TO WARNING;',
    '',
  ];

  // Enum types used by public tables
  const enums = await sql<{ typname: string; labels: string[] }[]>`
    SELECT t.typname,
           array_agg(e.enumlabel ORDER BY e.enumsortorder) AS labels
    FROM pg_type t
    JOIN pg_enum e ON e.enumtypid = t.oid
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public'
    GROUP BY t.typname
    ORDER BY t.typname
  `;
  for (const e of enums) {
    const labels = e.labels.map((l) => `'${l.replace(/'/g, "''")}'`).join(', ');
    pre.push(
      `DO $$ BEGIN CREATE TYPE ${quoteIdent(e.typname)} AS ENUM (${labels}); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`,
    );
  }
  if (enums.length) pre.push('');

  for (const tableName of tableNames) {
    const cols = await sql<{
      column_name: string;
      data_type: string;
      udt_name: string;
      is_nullable: string;
      column_default: string | null;
      character_maximum_length: number | null;
      numeric_precision: number | null;
      numeric_scale: number | null;
    }[]>`
      SELECT column_name, data_type, udt_name, is_nullable, column_default,
             character_maximum_length, numeric_precision, numeric_scale
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = ${tableName}
      ORDER BY ordinal_position
    `;

    if (!cols.length) continue;

    const colDefs = cols.map((c) => {
      const type = formatColumnType(c);
      const nullSql = c.is_nullable === 'YES' ? '' : ' NOT NULL';
      const def = c.column_default ? ` DEFAULT ${c.column_default}` : '';
      return `  ${quoteIdent(c.column_name)} ${type}${nullSql}${def}`;
    });

    const pk = await sql<{ column_name: string }[]>`
      SELECT a.attname AS column_name
      FROM pg_index i
      JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
      JOIN pg_class c ON c.oid = i.indrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public'
        AND c.relname = ${tableName}
        AND i.indisprimary
      ORDER BY array_position(i.indkey, a.attnum)
    `;

    let create = `CREATE TABLE IF NOT EXISTS ${quoteIdent(tableName)} (\n${colDefs.join(',\n')}`;
    if (pk.length) {
      create += `,\n  PRIMARY KEY (${pk.map((p) => quoteIdent(p.column_name)).join(', ')})`;
    }
    create += '\n);';
    pre.push(create);
    pre.push('');
  }

  // Foreign keys
  const fks = await sql<{
    constraint_name: string;
    table_name: string;
    column_name: string;
    foreign_table_name: string;
    foreign_column_name: string;
  }[]>`
    SELECT
      tc.constraint_name,
      tc.table_name,
      kcu.column_name,
      ccu.table_name AS foreign_table_name,
      ccu.column_name AS foreign_column_name
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
      ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
      ON ccu.constraint_name = tc.constraint_name AND ccu.table_schema = tc.table_schema
    WHERE tc.constraint_type = 'FOREIGN KEY'
      AND tc.table_schema = 'public'
      AND tc.table_name = ANY(${tableNames})
    ORDER BY tc.table_name, tc.constraint_name, kcu.ordinal_position
  `;

  type FkRow = {
    constraint_name: string;
    table_name: string;
    column_name: string;
    foreign_table_name: string;
    foreign_column_name: string;
  };
  const fkGroups = new Map<string, FkRow[]>();
  for (const fk of fks) {
    const key = `${fk.table_name}::${fk.constraint_name}`;
    const arr = fkGroups.get(key) || [];
    arr.push(fk);
    fkGroups.set(key, arr);
  }
  for (const group of fkGroups.values()) {
    const first = group[0];
    post.push(
      `DO $$ BEGIN
  ALTER TABLE ${quoteIdent(first.table_name)}
    ADD CONSTRAINT ${quoteIdent(first.constraint_name)}
    FOREIGN KEY (${group.map((g) => quoteIdent(g.column_name)).join(', ')})
    REFERENCES ${quoteIdent(first.foreign_table_name)} (${group.map((g) => quoteIdent(g.foreign_column_name)).join(', ')});
EXCEPTION WHEN duplicate_object THEN NULL; END $$;`,
    );
  }

  // Non-PK indexes
  const indexes = await sql<{ indexdef: string }[]>`
    SELECT pg_get_indexdef(i.indexrelid) AS indexdef
    FROM pg_index i
    JOIN pg_class c ON c.oid = i.indrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = ANY(${tableNames})
      AND NOT i.indisprimary
    ORDER BY c.relname
  `;
  for (const idx of indexes) {
    // IF NOT EXISTS for idempotent restore
    const def = idx.indexdef.replace(/^CREATE UNIQUE INDEX /, 'CREATE UNIQUE INDEX IF NOT EXISTS ')
      .replace(/^CREATE INDEX /, 'CREATE INDEX IF NOT EXISTS ');
    post.push(`${def};`);
  }

  // Reset sequences owned by columns
  post.push('');
  post.push('-- Sync sequences to MAX(column)');
  for (const tableName of tableNames) {
    const qualified = `public.${quoteIdent(tableName)}`;
    const seqCols = await sql.unsafe(
      `SELECT a.attname AS column_name,
              pg_get_serial_sequence('${qualified.replace(/'/g, "''")}', a.attname) AS seq
       FROM pg_attribute a
       JOIN pg_class c ON c.oid = a.attrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace
       WHERE n.nspname = 'public'
         AND c.relname = '${tableName.replace(/'/g, "''")}'
         AND a.attnum > 0
         AND NOT a.attisdropped`,
    ) as unknown as Array<{ column_name: string; seq: string | null }>;
    for (const sc of seqCols) {
      if (!sc.seq) continue;
      post.push(
        `SELECT setval(${literal(sc.seq)}, COALESCE((SELECT MAX(${quoteIdent(sc.column_name)}) FROM ${quoteIdent(tableName)}), 1), true);`,
      );
    }
  }

  return { preSql: `${pre.join('\n')}\n`, postSql: `${post.join('\n')}\n` };
}

function literal(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function formatColumnType(c: {
  data_type: string;
  udt_name: string;
  character_maximum_length: number | null;
  numeric_precision: number | null;
  numeric_scale: number | null;
}): string {
  if (c.data_type === 'USER-DEFINED') return quoteIdent(c.udt_name);
  if (c.data_type === 'ARRAY') {
    // udt_name like _text → text[]
    const base = c.udt_name.startsWith('_') ? c.udt_name.slice(1) : c.udt_name;
    return `${base}[]`;
  }
  if (c.data_type === 'character varying') {
    return c.character_maximum_length
      ? `character varying(${c.character_maximum_length})`
      : 'character varying';
  }
  if (c.data_type === 'numeric' && c.numeric_precision != null) {
    return c.numeric_scale != null
      ? `numeric(${c.numeric_precision},${c.numeric_scale})`
      : `numeric(${c.numeric_precision})`;
  }
  if (c.data_type === 'timestamp with time zone') return 'timestamptz';
  if (c.data_type === 'timestamp without time zone') return 'timestamp';
  if (c.data_type === 'double precision') return 'double precision';
  return c.data_type;
}
