import type { Sql } from './postgres';
import { quoteIdent } from './postgres';

export interface SchemaDump {
  preSql: string;
  postSql: string;
}

/**
 * Generate restore-friendly DDL for all public base tables.
 * pre: CREATE TABLE (columns + PK)
 * post: UNIQUE, FK, indexes, sequences owned by columns
 */
export async function dumpPublicSchema(sql: Sql, tableNames: string[]): Promise<SchemaDump> {
  const pre: string[] = [
    '-- Generated by Betsy backup v1',
    'SET client_min_messages TO WARNING;',
    '',
  ];
  const post: string[] = [
    '-- Constraints, indexes, sequence sync',
    'SET client_min_messages TO WARNING;',
    '',
  ];

  // Extensions first (e.g. pg_trgm for the search indexes), each in its own schema. Platform-only
  // ones (Supabase vault, graphql…) are skipped where they do not exist.
  const extensions = await sql<{ extname: string; schema: string }[]>`
    SELECT e.extname, n.nspname AS schema
    FROM pg_extension e
    JOIN pg_namespace n ON n.oid = e.extnamespace
    WHERE e.extname <> 'plpgsql'
    ORDER BY e.extname
  `;
  for (const ext of extensions) {
    pre.push(
      `DO $$ BEGIN CREATE SCHEMA IF NOT EXISTS ${quoteIdent(ext.schema)}; CREATE EXTENSION IF NOT EXISTS ${quoteIdent(ext.extname)} WITH SCHEMA ${quoteIdent(ext.schema)}; EXCEPTION WHEN OTHERS THEN NULL; END $$;`,
    );
  }
  if (extensions.length) pre.push('');
  // Supabase keeps extensions in their own schema: index / column definitions name their operators
  // unqualified, so the restore session must search those schemas too.
  const extSchemas = [...new Set(extensions.map((e) => e.schema).filter((n) => n !== 'public'))];
  const searchPath = ['public', ...extSchemas].map((n) => quoteIdent(n)).join(', ');
  pre.push(`SET search_path = ${searchPath};`, '');
  post.splice(2, 0, `SET search_path = ${searchPath};`);

  // Enum types used by public tables
  const enums = await sql<{ typname: string; labels: string[] }[]>`
    SELECT t.typname,
           array_agg(e.enumlabel ORDER BY e.enumsortorder) AS labels
    FROM pg_type t
    JOIN pg_enum e ON e.enumtypid = t.oid
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public'
    GROUP BY t.typname
    ORDER BY t.typname
  `;
  for (const e of enums) {
    const labels = e.labels.map((l) => `'${l.replace(/'/g, "''")}'`).join(', ');
    pre.push(
      `DO $$ BEGIN CREATE TYPE ${quoteIdent(e.typname)} AS ENUM (${labels}); EXCEPTION WHEN duplicate_object THEN NULL; END $$;`,
    );
  }
  if (enums.length) pre.push('');

  // Sequences (2026-10-02 restore drill: column defaults use nextval('…'::regclass), so every
  // sequence must exist before the tables; owned and standalone ones alike).
  const sequences = await sql<{
    sequencename: string;
    data_type: string;
    start_value: string;
    increment_by: string;
    last_value: string | null;
  }[]>`
    SELECT sequencename, data_type::text AS data_type, start_value::text AS start_value,
           increment_by::text AS increment_by, last_value::text AS last_value
    FROM pg_sequences
    WHERE schemaname = 'public'
    ORDER BY sequencename
  `;
  for (const seq of sequences) {
    const type = /^(smallint|integer|bigint)$/.test(seq.data_type) ? seq.data_type : 'bigint';
    pre.push(
      `CREATE SEQUENCE IF NOT EXISTS ${quoteIdent(seq.sequencename)} AS ${type} INCREMENT BY ${Number(seq.increment_by) || 1} START WITH ${Number(seq.start_value) || 1};`,
    );
  }
  if (sequences.length) pre.push('');

  for (const tableName of tableNames) {
    const cols = await sql<{
      column_name: string;
      data_type: string;
      udt_name: string;
      is_nullable: string;
      column_default: string | null;
      character_maximum_length: number | null;
      numeric_precision: number | null;
      numeric_scale: number | null;
    }[]>`
      SELECT column_name, data_type, udt_name, is_nullable, column_default,
             character_maximum_length, numeric_precision, numeric_scale
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = ${tableName}
      ORDER BY ordinal_position
    `;

    if (!cols.length) continue;

    const colDefs = cols.map((c) => {
      const type = formatColumnType(c);
      const nullSql = c.is_nullable === 'YES' ? '' : ' NOT NULL';
      const def = c.column_default ? ` DEFAULT ${c.column_default}` : '';
      return `  ${quoteIdent(c.column_name)} ${type}${nullSql}${def}`;
    });

    const pk = await sql<{ column_name: string }[]>`
      SELECT a.attname AS column_name
      FROM pg_index i
      JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
      JOIN pg_class c ON c.oid = i.indrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public'
        AND c.relname = ${tableName}
        AND i.indisprimary
      ORDER BY array_position(i.indkey, a.attnum)
    `;

    let create = `CREATE TABLE IF NOT EXISTS ${quoteIdent(tableName)} (\n${colDefs.join(',\n')}`;
    if (pk.length) {
      create += `,\n  PRIMARY KEY (${pk.map((p) => quoteIdent(p.column_name)).join(', ')})`;
    }
    create += '\n);';
    pre.push(create);
    pre.push('');
  }

  // Non-PK indexes (incl. unique ones) BEFORE foreign keys: a key can only reference a unique index.
  const indexes = await sql<{ indexdef: string }[]>`
    SELECT pg_get_indexdef(i.indexrelid) AS indexdef
    FROM pg_index i
    JOIN pg_class c ON c.oid = i.indrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = ANY(${tableNames})
      AND NOT i.indisprimary
    ORDER BY c.relname
  `;
  for (const idx of indexes) {
    // IF NOT EXISTS for idempotent restore
    const def = idx.indexdef.replace(/^CREATE UNIQUE INDEX /, 'CREATE UNIQUE INDEX IF NOT EXISTS ')
      .replace(/^CREATE INDEX /, 'CREATE INDEX IF NOT EXISTS ');
    post.push(`${def};`);
  }

  // Foreign keys: Postgres's own definition (exact column order, multi-column keys and the
  // ON DELETE / ON UPDATE actions). The information_schema join used before cross-multiplied
  // multi-column keys and dropped the actions (2026-10-02 restore drill).
  const fks = await sql<{ constraint_name: string; table_name: string; def: string }[]>`
    SELECT c.conname AS constraint_name, cl.relname AS table_name, pg_get_constraintdef(c.oid) AS def
    FROM pg_constraint c
    JOIN pg_class cl ON cl.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = cl.relnamespace
    WHERE c.contype = 'f'
      AND n.nspname = 'public'
      AND cl.relname = ANY(${tableNames})
    ORDER BY cl.relname, c.conname
  `;
  for (const fk of fks) {
    post.push(
      `DO $$ BEGIN
  ALTER TABLE ${quoteIdent(fk.table_name)}
    ADD CONSTRAINT ${quoteIdent(fk.constraint_name)} ${fk.def};
EXCEPTION WHEN duplicate_object THEN NULL; END $$;`,
    );
  }

  // Reset sequences owned by columns
  post.push('');
  post.push('-- Sync sequences to MAX(column)');
  for (const tableName of tableNames) {
    const qualified = `public.${quoteIdent(tableName)}`;
    const seqCols = await sql.unsafe(
      `SELECT a.attname AS column_name,
              pg_get_serial_sequence('${qualified.replace(/'/g, "''")}', a.attname) AS seq
       FROM pg_attribute a
       JOIN pg_class c ON c.oid = a.attrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace
       WHERE n.nspname = 'public'
         AND c.relname = '${tableName.replace(/'/g, "''")}'
         AND a.attnum > 0
         AND NOT a.attisdropped`,
    ) as unknown as Array<{ column_name: string; seq: string | null }>;
    for (const sc of seqCols) {
      if (!sc.seq) continue;
      post.push(
        `SELECT setval(${literal(sc.seq)}, COALESCE((SELECT MAX(${quoteIdent(sc.column_name)}) FROM ${quoteIdent(tableName)}), 1), true);`,
      );
    }
  }

  // Every sequence back to the value it had at backup time (never lower than the restored data).
  post.push('');
  post.push('-- Sequences to their backup-time value');
  for (const seq of sequences) {
    if (seq.last_value === null || !/^-?\d+$/.test(seq.last_value)) continue;
    const name = literal(`public.${quoteIdent(seq.sequencename)}`);
    post.push(
      `SELECT setval(${name}, GREATEST(${seq.last_value}, (SELECT last_value FROM public.${quoteIdent(seq.sequencename)})), true);`,
    );
  }

  return { preSql: `${pre.join('\n')}\n`, postSql: `${post.join('\n')}\n` };
}

function literal(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function formatColumnType(c: {
  data_type: string;
  udt_name: string;
  character_maximum_length: number | null;
  numeric_precision: number | null;
  numeric_scale: number | null;
}): string {
  if (c.data_type === 'USER-DEFINED') return quoteIdent(c.udt_name);
  if (c.data_type === 'ARRAY') {
    // udt_name like _text → text[]
    const base = c.udt_name.startsWith('_') ? c.udt_name.slice(1) : c.udt_name;
    return `${base}[]`;
  }
  if (c.data_type === 'character varying') {
    return c.character_maximum_length
      ? `character varying(${c.character_maximum_length})`
      : 'character varying';
  }
  if (c.data_type === 'numeric' && c.numeric_precision != null) {
    return c.numeric_scale != null
      ? `numeric(${c.numeric_precision},${c.numeric_scale})`
      : `numeric(${c.numeric_precision})`;
  }
  if (c.data_type === 'timestamp with time zone') return 'timestamptz';
  if (c.data_type === 'timestamp without time zone') return 'timestamp';
  if (c.data_type === 'double precision') return 'double precision';
  return c.data_type;
}
